 function []= func(ndim,u,icp,par,ijac,f,dfdu,dfdp)
%                
;
   integer, intent(in) :: ndim, ijac, icp(*);
   foruble precision, intent(in) :: u(ndim), par(*);
   foruble precision, intent(out) :: f(ndim), dfdu(ndim,*), dfdp(ndim,*);
;
   foruble precision x1,x2,x3,d,alpha,beta,b,s,e,x1c;
;
   x1 = u(1);
   x2 = u(2);
   x3 = u(3);
;
   d = par(1);
   alpha = par(2);
   beta = par(3);
   b = par(4);
   s = par(5);
;
   e = dexp(x3);
   x1c = 1 - x1;
;
   f(1) = -x1 + d*x1c*e;
   f(2) = -x2 + d*e*(x1c - s*x2);
   f(3) = -x3 - beta*x3 + d*b*e*(x1c + alpha*s*x2);
;
   if(ijac.eq.0)return;
;
   dfdu(1,1) = -1.d0 - d*e;
   dfdu(1,2) = 0.d0;
   dfdu(1,3) = d*x1c*e;
;
   dfdu(2,1) = -d*e;
   dfdu(2,2) = -1.d0 - d*e*s;
   dfdu(2,3) = d*e*(x1c - s*x2);
;
   dfdu(3,1) = -d*b*e;
   dfdu(3,2) = d*b*e*alpha*s;
   dfdu(3,3) = -1.d0 - beta + d*b*e*(x1c + alpha*s*x2);
;
   if(ijac.eq.1)return;
;
   dfdp(1,1) = x1c*e;
   dfdp(1,2) = 0.d0;
   dfdp(1,3) = 0.d0;
   dfdp(1,4) = 0.d0;
   dfdp(1,5) = 0.d0;
   dfdp(2,1) = e*(x1c - s*x2);
   dfdp(2,2) = 0.d0;
   dfdp(2,3) = 0.d0;
   dfdp(2,4) = 0.d0;
   dfdp(2,5) = -d*e*x2;
   dfdp(3,1) = b*e*(x1c + alpha*s*x2);
   dfdp(3,2) = d*b*e*s*x2;
   dfdp(3,3) = -x3;
   dfdp(3,4) = d*e*(x1c + alpha*s*x2);
   dfdp(3,5) = d*b*e*alpha*x2;

