      MODULE AUTO_CONSTANTS
!
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INCLUDE 'auto.h'
!
      INTEGER NDIM,IPS,IRS,ILP
      INTEGER NICP
      INTEGER ICP(2*NPARX)
      INTEGER NTST,NCOL,IAD,ISP,ISW,IPLT,NBC,NINT
      INTEGER NMX
      DOUBLE PRECISION RL0,RL1,A0,A1
      INTEGER NPR,MXBF,IID,ITMX,ITNW,NWTN,JAC
      DOUBLE PRECISION EPSL,EPSU,EPSS
      DOUBLE PRECISION DS,DSMIN,DSMAX
      INTEGER IADS
      INTEGER NTHL
      INTEGER,ALLOCATABLE :: ITHL(:)
      DOUBLE PRECISION,ALLOCATABLE :: THL(:),VTHL(:)
      INTEGER NTHU
      DOUBLE PRECISION,ALLOCATABLE :: THU(:)
      INTEGER NUZR
      INTEGER, ALLOCATABLE :: IUZ(:)
      DOUBLE PRECISION,ALLOCATABLE :: VUZ(:)
!
! new global variables added for passing extra outputs 
! from function file
! NOUTX : maximum number of outputs that will be written if output exists
      INTEGER NOUTX
      INTEGER ODIM
      DOUBLE PRECISION,ALLOCATABLE :: OUT(:)
!
!
! Run options
      INTEGER RUNMODEDST,FORT2DST,FORT3DST,FORT7DST,FORT8DST,FORT9DST
      CHARACTER(63) FUNCFILENAME
      CHARACTER(63) STPNTFILENAME
      CHARACTER(63) BCNDFILENAME
      CHARACTER(63) ICNDFILENAME
      CHARACTER(63) FOPTFILENAME
      CHARACTER(63) PVLSFILENAME
!      
!     New global variables for Dynamical Systems Toolbox
      INTEGER NDIMDST,NOUTXDST,IPSDST,IRSDST,ILPDST
      INTEGER NICPDST
      INTEGER ICPDST(2*NPARX)
      INTEGER NTSTDST,NCOLDST,IADDST,ISPDST,ISWDST,IPLTDST,NBCDST
      INTEGER NINTDST
      INTEGER NMXDST
      DOUBLE PRECISION RL0DST,RL1DST,A0DST,A1DST
      INTEGER NPRDST,MXBFDST,IIDDST,ITMXDST,ITNWDST,NWTNDST,JACDST
      DOUBLE PRECISION EPSLDST,EPSUDST,EPSSDST
      DOUBLE PRECISION DSDST,DSMINDST,DSMAXDST
      INTEGER IADSDST
      INTEGER NTHLDST
      INTEGER,ALLOCATABLE :: ITHLDST(:)
      DOUBLE PRECISION,ALLOCATABLE :: THLDST(:),VTHLDST(:)
      INTEGER NTHUDST
      INTEGER,ALLOCATABLE :: ITHUDST(:)
      DOUBLE PRECISION,ALLOCATABLE :: VTHUDST(:)
      INTEGER NUZRDST
      INTEGER, ALLOCATABLE :: IUZDST(:)
      DOUBLE PRECISION,ALLOCATABLE :: VUZDST(:)
!
!
! Initial conditions passed from object to AUTO
      DOUBLE PRECISION,ALLOCATABLE :: PARDST0(:)
      DOUBLE PRECISION,ALLOCATABLE :: UDST0(:) 
      DOUBLE PRECISION,ALLOCATABLE :: OUTDST0(:)
!
! F7 objects
      INTEGER,ALLOCATABLE :: IBRF7(:)
      INTEGER,ALLOCATABLE :: oldIBRF7(:)
      INTEGER,ALLOCATABLE :: MTOTF7(:)
      INTEGER,ALLOCATABLE :: oldMTOTF7(:)
      INTEGER,ALLOCATABLE :: ITPF7(:)
      INTEGER,ALLOCATABLE :: oldITPF7(:)
      INTEGER,ALLOCATABLE :: LABF7(:)
      INTEGER,ALLOCATABLE :: oldLABF7(:)
      DOUBLE PRECISION,ALLOCATABLE :: PARF7(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldPARF7(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: VAXISF7(:)
      DOUBLE PRECISION,ALLOCATABLE :: oldVAXISF7(:)
      DOUBLE PRECISION,ALLOCATABLE :: UF7(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldUF7(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: OUTF7(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldOUTF7(:,:)
!      
! F8 objects    
      INTEGER ILAB
      INTEGER,ALLOCATABLE :: IBRF8(:)
      INTEGER,ALLOCATABLE :: oldIBRF8(:)
      INTEGER,ALLOCATABLE :: MTOTF8(:)
      INTEGER,ALLOCATABLE :: oldMTOTF8(:)
      INTEGER,ALLOCATABLE :: ITPF8(:)
      INTEGER,ALLOCATABLE :: oldITPF8(:)
      INTEGER,ALLOCATABLE :: LABF8(:)
      INTEGER,ALLOCATABLE :: oldLABF8(:)
      INTEGER,ALLOCATABLE :: NFPRF8(:)
      INTEGER,ALLOCATABLE :: oldNFPRF8(:)
      INTEGER,ALLOCATABLE :: ISWF8(:)
      INTEGER,ALLOCATABLE :: oldISWF8(:)
      INTEGER,ALLOCATABLE :: NTPLF8(:)
      INTEGER,ALLOCATABLE :: oldNTPLF8(:)
      INTEGER,ALLOCATABLE :: NARF8(:)
      INTEGER,ALLOCATABLE :: oldNARF8(:)
      INTEGER,ALLOCATABLE :: NROWPRF8(:)
      INTEGER,ALLOCATABLE :: oldNROWPRF8(:)
      INTEGER,ALLOCATABLE :: NTSTF8(:)
      INTEGER,ALLOCATABLE :: oldNTSTF8(:)
      INTEGER,ALLOCATABLE :: NCOLF8(:)
      INTEGER,ALLOCATABLE :: oldNCOLF8(:)
      INTEGER,ALLOCATABLE :: NPARXF8(:)
      INTEGER,ALLOCATABLE :: oldNPARXF8(:)
      INTEGER,ALLOCATABLE :: IFPRF8(:,:)
      INTEGER,ALLOCATABLE :: oldIFPRF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: TF8(:)
      DOUBLE PRECISION,ALLOCATABLE :: oldTF8(:)
      DOUBLE PRECISION,ALLOCATABLE :: TMF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldTMF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: TMF8TMP(:)
      DOUBLE PRECISION,ALLOCATABLE :: PARF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldPARF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: RLDOTF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldRLDOTF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: UF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldUF8(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: UPSF8(:,:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldUPSF8(:,:,:)
      DOUBLE PRECISION,ALLOCATABLE :: UPSF8TMP(:,:)
      DOUBLE PRECISION,ALLOCATABLE :: UDOTPSF8(:,:,:)
      DOUBLE PRECISION,ALLOCATABLE :: oldUDOTPSF8(:,:,:)
      DOUBLE PRECISION,ALLOCATABLE :: UDOTPSF8TMP(:,:)
!      
      END MODULE AUTO_CONSTANTS
!    