! DUMMY FILE, USED IN CASE MPI IS NOT AVAILABLE.
 
      SUBROUTINE MPIINI(IAP)
      INTEGER IAP(*)
      IAP(38) = 0 ! IAM
      IAP(39) = 1 ! KWT
      END SUBROUTINE MPIINI
 
      SUBROUTINE MPIIAP(IAP)
      END SUBROUTINE MPIIAP
 
      SUBROUTINE MPIWFI(AUTOBV,FUNI,ICNI)
      LOGICAL :: AUTOBV
      EXTERNAL FUNI,ICNI
      END SUBROUTINE MPIWFI
 
      SUBROUTINE MPICON(S1,A1,A2,BB,CC,D,FAA,FC,NTST,NOV,NCB,NRC,IFST)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      END SUBROUTINE MPICON
 
      SUBROUTINE MPISBV(IAP,RAP,PAR,ICP,RLDOT,NRA,UPS,UOLDPS,UDOTPS,
     & UPOLDP,DTM,THU,IFST,NLLV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      END SUBROUTINE MPISBV
 
      SUBROUTINE MPIBCAST(BUF,LEN)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      END SUBROUTINE MPIBCAST
 
      SUBROUTINE MPISCAT(BUF,NDX,N,IADD)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      END SUBROUTINE MPISCAT
 
      SUBROUTINE MPIGAT(BUF,NDX,N)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      END SUBROUTINE MPIGAT
 
      SUBROUTINE MPIEND()
      END SUBROUTINE MPIEND
 
      SUBROUTINE MPITIM(TIM)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      END SUBROUTINE MPITIM  


