!---------------------------------------------------------------------
      SUBROUTINE DEALLOCATEIN()      
!
      USE AUTO_CONSTANTS
!
! For constants
      IF(ALLOCATED(ITHLDST))DEALLOCATE(ITHLDST)
      IF(ALLOCATED(VTHLDST))DEALLOCATE(VTHLDST)
      IF(ALLOCATED(ITHUDST))DEALLOCATE(ITHUDST)
      IF(ALLOCATED(VTHUDST))DEALLOCATE(VTHUDST)
      IF(ALLOCATED(IUZDST))DEALLOCATE(IUZDST)
      IF(ALLOCATED(VUZDST))DEALLOCATE(VUZDST)
! For STPNT
      IF(ALLOCATED(PARDST0))DEALLOCATE(PARDST0)
      IF(ALLOCATED(UDST0))DEALLOCATE(UDST0)
      IF(ALLOCATED(OUTDST0))DEALLOCATE(OUTDST0)
!
      RETURN
      END       
!
