c----------------------------------------------------------------------;
c----------------------------------------------------------------------;
if isempty(ne), ne=2; end;
if isempty(nx), nx=6 ; end;
c----------------------------------------------------------------------;
c----------------------------------------------------------------------;
c     brf  :  a parabolic pde(the brusselator);
c----------------------------------------------------------------------;
c----------------------------------------------------------------------;
c(discretized in space by fourth order finite differences);
c----------------------------------------------------------------------;
c----------------------------------------------------------------------;
c note: the values of the constants ne and nx are defined above.;
c       ifmlv they are changed then the equations-file brf.f must;
c       be rewritten with an editor or with the gui write button.;
c;
c      ne  :  the dimension of the pde !;
c      nx  :  the number of space intervals forml the discretization;
c;
c the auto-constant ndim must be set equal to the value of ne.*(nx-1);
c----------------------------------------------------------------------;
c----------------------------------------------------------------------;
